/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateEscrowRouteImport } from './routes/create-escrow'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as TestDrainRouteImport } from './routes/test-drain'
import { Route as EscrowActiveRouteImport } from './routes/escrow.active'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateEscrowRoute = CreateEscrowRouteImport.update({
  id: '/create-escrow',
  path: '/create-escrow',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const TestDrainRoute = TestDrainRouteImport.update({
  id: '/test-drain',
  path: '/test-drain',
  getParentRoute: () => rootRouteImport,
} as any)
const EscrowActiveRoute = EscrowActiveRouteImport.update({
  id: '/escrow/active',
  path: '/escrow/active',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-escrow': typeof CreateEscrowRoute
  '/dashboard': typeof DashboardRoute
  '/success': typeof SuccessRoute
  '/test-drain': typeof TestDrainRoute
  '/escrow/active': typeof EscrowActiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-escrow': typeof CreateEscrowRoute
  '/dashboard': typeof DashboardRoute
  '/success': typeof SuccessRoute
  '/test-drain': typeof TestDrainRoute
  '/escrow/active': typeof EscrowActiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-escrow': typeof CreateEscrowRoute
  '/dashboard': typeof DashboardRoute
  '/success': typeof SuccessRoute
  '/test-drain': typeof TestDrainRoute
  '/escrow/active': typeof EscrowActiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-escrow'
    | '/dashboard'
    | '/success'
    | '/test-drain'
    | '/escrow/active'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-escrow'
    | '/dashboard'
    | '/success'
    | '/test-drain'
    | '/escrow/active'
  id:
    | '__root__'
    | '/'
    | '/create-escrow'
    | '/dashboard'
    | '/success'
    | '/test-drain'
    | '/escrow/active'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateEscrowRoute: typeof CreateEscrowRoute
  DashboardRoute: typeof DashboardRoute
  SuccessRoute: typeof SuccessRoute
  TestDrainRoute: typeof TestDrainRoute
  EscrowActiveRoute: typeof EscrowActiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-escrow': {
      id: '/create-escrow'
      path: '/create-escrow'
      fullPath: '/create-escrow'
      preLoaderRoute: typeof CreateEscrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-drain': {
      id: '/test-drain'
      path: '/test-drain'
      fullPath: '/test-drain'
      preLoaderRoute: typeof TestDrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escrow/active': {
      id: '/escrow/active'
      path: '/escrow/active'
      fullPath: '/escrow/active'
      preLoaderRoute: typeof EscrowActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateEscrowRoute: CreateEscrowRoute,
  DashboardRoute: DashboardRoute,
  SuccessRoute: SuccessRoute,
  TestDrainRoute: TestDrainRoute,
  EscrowActiveRoute: EscrowActiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
